// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MoodNest",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "MoodNest",
            targets: ["AppModule"],
            bundleIdentifier: "com.PiyushPal34.MoodNest",
            teamIdentifier: "788P3925GD",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            exclude: ["Assets.xcassets", "Resources/JSON/DailyPrompts.json", "Resources/JSON/DailyQuotes.json", "Resources/JSON/MiniGuides.json", "Resources/JSON/WellnessTips.json"],
            resources: [
                .process("Assets.xcassets"),
                .process("Resources/JSON/DailyPrompts.json"),
                .process("Resources/JSON/DailyQuotes.json"),
                .process("Resources/JSON/MiniGuides.json"),
                .process("Resources/JSON/WellnessTips.json")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)